const textSobre = [`
A Pepper Smith é muito mais do que uma simples lanchonete. Somos um lugar onde sabor, qualidade e paixão pela comida se encontram para criar uma experiência gastronômica única. Desde a nossa fundação, nos dedicamos a oferecer aos nossos clientes um cardápio diversificado, repleto de opções deliciosas e preparadas com ingredientes frescos e selecionados.
Nossa equipe é formada por profissionais apaixonados pela culinária e pela arte de servir. Cada prato que sai de nossa cozinha é cuidadosamente preparado com atenção aos detalhes, garantindo que cada mordida seja uma explosão de sabores e texturas. Estamos sempre em busca de novas criações e inspirações, para surpreender e encantar os paladares mais exigentes.
Em um ambiente acolhedor e descontraído, a Pepper Smith convida você a desfrutar de momentos especiais com amigos e familiares. Nossas mesas são um convite para boas conversas e risadas contagiantes, enquanto você saboreia nossos hambúrgueres suculentos, sanduíches irresistíveis, batatas crocantes e milkshakes cremosos.
`,
`Acreditamos na importância de utilizar ingredientes frescos e de alta qualidade em nossas receitas. Por isso, trabalhamos em parceria com fornecedores locais, valorizando os produtores da nossa região. Ao escolher a Pepper Smith, você não apenas saboreia pratos deliciosos, mas também contribui para o fortalecimento da economia local e a sustentabilidade.
Além de nossas opções de menu tradicionais, também oferecemos alternativas vegetarianas e veganas, para atender às diferentes preferências alimentares. Queremos que todos se sintam bem-vindos em nossa lanchonete e tenham a oportunidade de desfrutar de uma refeição saborosa e satisfatória.
Na Pepper Smith, o atendimento ao cliente é uma prioridade. Nossa equipe está sempre pronta para receber você com um sorriso caloroso e garantir que sua experiência seja memorável. Queremos que você se sinta em casa, aproveitando cada momento e cada sabor.
Seja para uma refeição rápida durante o expediente, um encontro descontraído com os amigos ou um almoço em família, a Pepper Smith é o lugar perfeito. Venha nos visitar e descubra por que somos mais do que uma simples lanchonete. Somos a combinação perfeita entre sabor, qualidade e momentos inesquecíveis. Estamos ansiosos para recebê-lo e proporcionar uma experiência gastronômica incrível`];


const a = [`Os coquetéis da Pepper Smith são verdadeiras obras de arte líquida, projetadas para satisfazer os paladares mais exigentes e surpreender os amantes de bebidas especiais. Nossa equipe de mixologistas talentosos é apaixonada por criar combinações únicas e balanceadas, utilizando os melhores ingredientes e técnicas de preparo.
Cada coquetel é cuidadosamente elaborado, desde a seleção dos destilados até a escolha dos ingredientes frescos e complementares. Nossa carta de coquetéis oferece uma variedade incrível de opções, desde clássicos reinventados até criações exclusivas, garantindo que haja algo para todos os gostos.`,
`Se você é fã dos clássicos, nossos mixologistas são especialistas em preparar coquetéis como o Mojito, Margarita, Old Fashioned e Negroni, com uma pitada de criatividade e um toque especial. Cada gole é uma explosão de sabores equilibrados, onde cada ingrediente se destaca, proporcionando uma experiência única e memorável.`+
`Além dos coquetéis clássicos, oferecemos também criações autorais que refletem a essência da Pepper Smith. Nossos mixologistas estão sempre experimentando novas combinações de sabores, incorporando ingredientes frescos da estação e explorando técnicas de infusão e maceração para criar coquetéis exclusivos que irão surpreender até os mais experientes apreciadores.`,
`Quer você prefira coquetéis refrescantes e frutados, ou uma mistura mais complexa e intensa, nossa equipe está pronta para preparar a bebida perfeita para você. E se você tiver alguma preferência ou pedido especial, estamos sempre abertos a personalizar os coquetéis de acordo com suas preferências individuais.`];

export {textSobre,a}